name: plcart_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  debug_server_utils:
    git:
      url: https://github.com/AndreiLosev/plcart_debug_server_utils.git
  future_soket: ^1.0.0
  termansi: ^0.3.1
  termlib: ^0.4.0
  termparser: ^0.3.0
  path: ^1.8.0
  yaml: ^3.1.2
  args: ^2.7.0
  dartssh2: ^2.13.0

dev_dependencies:
  build_runner: ^2.4.11
  lints: ^3.0.0
  test: ^1.24.0
